#!/bin/bash

CWD=`pwd`
BUILD_DIR=$CWD/build
SOURCE_DIR=$CWD/sources
TEMPLATE_DIR=$CWD/templates

# source oe build env script
. $SOURCE_DIR/poky/oe-init-build-env

# copy bblayers conf to local conf path
cp $TEMPLATE_DIR/bblayers.conf.sample $BUILD_DIR/conf/bblayers.conf